### ISSUE TITLE
no module named urllib.parse

### ISSUE THREAD

**Issue by lucakiebel** [rhiever/reddit-twitter-bot#5]
Hey!
I have a problem using the script.
When I try starting it, bash says: 

> Traceback (most recent call last):
>   File "reddit_twitter_bot.py", line 27, in <module>
>     import urllib.parse
> ImportError: No module named parse

I tried searching for and installing urllib.parse, but it doesn't seem to work.

I am on Ubuntu 15.10 if that makes any difference!
- Luca

**Comment by rhiever** [comment]
What version of Python are you running?

**Comment by Siriusa77II** [comment]
Hi!  
I have same problem...  
i run python 2.7 and python  3.4.2  
i'm sorry for answer this verry old issue.  

`root@Lyra:~/bot/twitter/reddit# python reddit_twitter_bot.py  
Traceback (most recent call last):  
  File "reddit_twitter_bot.py", line 27, in <module>  
    import urllib.parse  
ImportError: No module named parse`

**Comment by AddaxSoft** [comment]
this solved the problem for me:

`pip install six`

then modify the import line 27 to:
```
#import urllib.parse
from six.moves.urllib.parse import urlparse
```
